# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d80b5b022dcf736bb3fea1ae9472e707a753f2810db9dd635aa37db5f6c857a5e63700c05ba3237275b743353cc76fa5f6b4c6769aa3e219f13e1e104858f61c

test:
  secret_key_base: c5530dea3b4abbda0ed3b175c56e642d953ebd901c13bfedc710ee6b25bf84578c687944195bd8e226e2bc5d1cdac1c58d94d8ce80bc9b20154110ad902173e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
